name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    if: github.ref == 'refs/heads/main'  # Prevent running on gh-pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

       - name: Clean build directory
        run: rm -rf dist

      - name: Build with Vite
        run: npm run build # This will now use the base path defined in package.json
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_TMDB_BASE_URL: ${{ secrets.VITE_TMDB_BASE_URL }}
          VITE_TMDB_API_KEY: ${{ secrets.VITE_TMDB_API_KEY }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
